def decode_qr(image_path: str, try_harder: bool | None) -> str | None: ...
def decode_qr_bytes(file_bytes: bytes, width: int, height: int, try_harder: bool | None) -> str | None: ...
def decode_qrs(image_path: str, try_harder: bool | None) -> list[str]: ...
def decode_qrs_bytes(file_bytes: bytes, width: int, height: int, try_harder: bool | None) -> list[str]: ...